// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Message_2eproto

#include <google/protobuf/port_def.inc>
#include <limits>
#include <string>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/message.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>

#include <google/protobuf/port_undef.inc>

#include "../../MP3-Lib/Source/ID3v2TagHeader.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Message_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_Message_2eproto;
namespace Message {
class Request;
struct RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
struct ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
}  // namespace Message
PROTOBUF_NAMESPACE_OPEN
template <>
::Message::Request* Arena::CreateMaybeMessage<::Message::Request>(Arena*);
template <>
::Message::Response* Arena::CreateMaybeMessage<::Message::Response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Message {

enum Request_RequestType : int {
  Request_RequestType_GET_ID3_TAG = 0,
  Request_RequestType_START_STREAMING = 1,
  Request_RequestType_STOP_STREAMING = 2,
  Request_RequestType_Request_RequestType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<int32_t>::min(),
  Request_RequestType_Request_RequestType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<int32_t>::max()
};
bool Request_RequestType_IsValid(int value);
constexpr Request_RequestType Request_RequestType_RequestType_MIN =
    Request_RequestType_GET_ID3_TAG;
constexpr Request_RequestType Request_RequestType_RequestType_MAX =
    Request_RequestType_STOP_STREAMING;
constexpr int Request_RequestType_RequestType_ARRAYSIZE =
    Request_RequestType_RequestType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Request_RequestType_descriptor();
template <typename T>
inline const std::string& Request_RequestType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Request_RequestType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to function Request_RequestType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
      Request_RequestType_descriptor(), enum_t_value);
}
inline bool Request_RequestType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
    Request_RequestType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Request_RequestType>(
      Request_RequestType_descriptor(), name, value);
}
enum Response_ResponseType : int {
  Response_ResponseType_SUCCESS = 0,
  Response_ResponseType_Response_ResponseType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<int32_t>::min(),
  Response_ResponseType_Response_ResponseType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<int32_t>::max()
};
bool Response_ResponseType_IsValid(int value);
constexpr Response_ResponseType Response_ResponseType_ResponseType_MIN =
    Response_ResponseType_SUCCESS;
constexpr Response_ResponseType Response_ResponseType_ResponseType_MAX =
    Response_ResponseType_SUCCESS;
constexpr int Response_ResponseType_ResponseType_ARRAYSIZE =
    Response_ResponseType_ResponseType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
Response_ResponseType_descriptor();
template <typename T>
inline const std::string& Response_ResponseType_Name(T enum_t_value) {
  static_assert(
      ::std::is_same<T, Response_ResponseType>::value ||
          ::std::is_integral<T>::value,
      "Incorrect type passed to function Response_ResponseType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
      Response_ResponseType_descriptor(), enum_t_value);
}
inline bool Response_ResponseType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
    Response_ResponseType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<
      Response_ResponseType>(Response_ResponseType_descriptor(), name, value);
}
// ===================================================================

class Request final : public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Message.Request)
                                                               */
{
 public:
  inline Request() : Request(nullptr) {}
  ~Request() override;
  explicit PROTOBUF_CONSTEXPR Request(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Request(const Request& from);
  Request(Request&& from) noexcept : Request() { *this = ::std::move(from); }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(&_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;

  friend void swap(Request& a, Request& b) { a.Swap(&b); }
  inline void Swap(Request* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Request& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Request& from) { Request::MergeImpl(*this, from); }

 private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg,
                        const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);

 public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(
      const char* ptr,
      ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target,
      ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

 private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);

 private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Message.Request";
  }

 protected:
  explicit Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                   bool is_message_owned = false);

 public:
  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData* GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Request_RequestType RequestType;
  static constexpr RequestType GET_ID3_TAG = Request_RequestType_GET_ID3_TAG;
  static constexpr RequestType START_STREAMING =
      Request_RequestType_START_STREAMING;
  static constexpr RequestType STOP_STREAMING =
      Request_RequestType_STOP_STREAMING;
  static inline bool RequestType_IsValid(int value) {
    return Request_RequestType_IsValid(value);
  }
  static constexpr RequestType RequestType_MIN =
      Request_RequestType_RequestType_MIN;
  static constexpr RequestType RequestType_MAX =
      Request_RequestType_RequestType_MAX;
  static constexpr int RequestType_ARRAYSIZE =
      Request_RequestType_RequestType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  RequestType_descriptor() {
    return Request_RequestType_descriptor();
  }
  template <typename T>
  static inline const std::string& RequestType_Name(T enum_t_value) {
    static_assert(
        ::std::is_same<T, RequestType>::value || ::std::is_integral<T>::value,
        "Incorrect type passed to function RequestType_Name.");
    return Request_RequestType_Name(enum_t_value);
  }
  static inline bool RequestType_Parse(
      ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RequestType* value) {
    return Request_RequestType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
  };
  // .Message.Request.RequestType type = 1;
  void clear_type();
  ::Message::Request_RequestType type() const;
  void set_type(::Message::Request_RequestType value);

 private:
  ::Message::Request_RequestType _internal_type() const;
  void _internal_set_type(::Message::Request_RequestType value);

 public:
  // @@protoc_insertion_point(class_scope:Message.Request)
 private:
  class _Internal;

  template <typename T>
  friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union {
    Impl_ _impl_;
  };
  friend struct ::TableStruct_Message_2eproto;
};
// -------------------------------------------------------------------

class Response final : public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Message.Response)
                                                                */
{
 public:
  inline Response() : Response(nullptr) {}
  ~Response() override;
  explicit PROTOBUF_CONSTEXPR Response(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Response(const Response& from);
  Response(Response&& from) noexcept : Response() { *this = ::std::move(from); }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Response& default_instance() {
    return *internal_default_instance();
  }
  enum DataCase {
    kId3V2Tag = 1,
    kResponse = 2,
    DATA_NOT_SET = 0,
  };

  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(&_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;

  friend void swap(Response& a, Response& b) { a.Swap(&b); }
  inline void Swap(Response* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Response& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Response& from) { Response::MergeImpl(*this, from); }

 private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg,
                        const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);

 public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(
      const char* ptr,
      ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target,
      ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

 private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);

 private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Message.Response";
  }

 protected:
  explicit Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                    bool is_message_owned = false);

 public:
  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData* GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Response_ResponseType ResponseType;
  static constexpr ResponseType SUCCESS = Response_ResponseType_SUCCESS;
  static inline bool ResponseType_IsValid(int value) {
    return Response_ResponseType_IsValid(value);
  }
  static constexpr ResponseType ResponseType_MIN =
      Response_ResponseType_ResponseType_MIN;
  static constexpr ResponseType ResponseType_MAX =
      Response_ResponseType_ResponseType_MAX;
  static constexpr int ResponseType_ARRAYSIZE =
      Response_ResponseType_ResponseType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ResponseType_descriptor() {
    return Response_ResponseType_descriptor();
  }
  template <typename T>
  static inline const std::string& ResponseType_Name(T enum_t_value) {
    static_assert(
        ::std::is_same<T, ResponseType>::value || ::std::is_integral<T>::value,
        "Incorrect type passed to function ResponseType_Name.");
    return Response_ResponseType_Name(enum_t_value);
  }
  static inline bool ResponseType_Parse(
      ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ResponseType* value) {
    return Response_ResponseType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kId3V2TagFieldNumber = 1,
    kResponseFieldNumber = 2,
  };
  // .ID3v2.ID3v2Tag id3v2Tag = 1;
  bool has_id3v2tag() const;

 private:
  bool _internal_has_id3v2tag() const;

 public:
  void clear_id3v2tag();
  const ::ID3v2::ID3v2Tag& id3v2tag() const;
  PROTOBUF_NODISCARD ::ID3v2::ID3v2Tag* release_id3v2tag();
  ::ID3v2::ID3v2Tag* mutable_id3v2tag();
  void set_allocated_id3v2tag(::ID3v2::ID3v2Tag* id3v2tag);

 private:
  const ::ID3v2::ID3v2Tag& _internal_id3v2tag() const;
  ::ID3v2::ID3v2Tag* _internal_mutable_id3v2tag();

 public:
  void unsafe_arena_set_allocated_id3v2tag(::ID3v2::ID3v2Tag* id3v2tag);
  ::ID3v2::ID3v2Tag* unsafe_arena_release_id3v2tag();

  // .Message.Response.ResponseType response = 2;
  bool has_response() const;

 private:
  bool _internal_has_response() const;

 public:
  void clear_response();
  ::Message::Response_ResponseType response() const;
  void set_response(::Message::Response_ResponseType value);

 private:
  ::Message::Response_ResponseType _internal_response() const;
  void _internal_set_response(::Message::Response_ResponseType value);

 public:
  void clear_data();
  DataCase data_case() const;
  // @@protoc_insertion_point(class_scope:Message.Response)
 private:
  class _Internal;
  void set_has_id3v2tag();
  void set_has_response();

  inline bool has_data() const;
  inline void clear_has_data();

  template <typename T>
  friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union DataUnion {
      constexpr DataUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::ID3v2::ID3v2Tag* id3v2tag_;
      int response_;
    } data_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];
  };
  union {
    Impl_ _impl_;
  };
  friend struct ::TableStruct_Message_2eproto;
};
// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request

// .Message.Request.RequestType type = 1;
inline void Request::clear_type() { _impl_.type_ = 0; }
inline ::Message::Request_RequestType Request::_internal_type() const {
  return static_cast<::Message::Request_RequestType>(_impl_.type_);
}
inline ::Message::Request_RequestType Request::type() const {
  // @@protoc_insertion_point(field_get:Message.Request.type)
  return _internal_type();
}
inline void Request::_internal_set_type(::Message::Request_RequestType value) {
  _impl_.type_ = value;
}
inline void Request::set_type(::Message::Request_RequestType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:Message.Request.type)
}

// -------------------------------------------------------------------

// Response

// .ID3v2.ID3v2Tag id3v2Tag = 1;
inline bool Response::_internal_has_id3v2tag() const {
  return data_case() == kId3V2Tag;
}
inline bool Response::has_id3v2tag() const { return _internal_has_id3v2tag(); }
inline void Response::set_has_id3v2tag() { _impl_._oneof_case_[0] = kId3V2Tag; }
inline ::ID3v2::ID3v2Tag* Response::release_id3v2tag() {
  // @@protoc_insertion_point(field_release:Message.Response.id3v2Tag)
  if (_internal_has_id3v2tag()) {
    clear_has_data();
    ::ID3v2::ID3v2Tag* temp = _impl_.data_.id3v2tag_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.data_.id3v2tag_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::ID3v2::ID3v2Tag& Response::_internal_id3v2tag() const {
  return _internal_has_id3v2tag() ? *_impl_.data_.id3v2tag_
                                  : reinterpret_cast<::ID3v2::ID3v2Tag&>(
                                        ::ID3v2::_ID3v2Tag_default_instance_);
}
inline const ::ID3v2::ID3v2Tag& Response::id3v2tag() const {
  // @@protoc_insertion_point(field_get:Message.Response.id3v2Tag)
  return _internal_id3v2tag();
}
inline ::ID3v2::ID3v2Tag* Response::unsafe_arena_release_id3v2tag() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Message.Response.id3v2Tag)
  if (_internal_has_id3v2tag()) {
    clear_has_data();
    ::ID3v2::ID3v2Tag* temp = _impl_.data_.id3v2tag_;
    _impl_.data_.id3v2tag_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Response::unsafe_arena_set_allocated_id3v2tag(
    ::ID3v2::ID3v2Tag* id3v2tag) {
  clear_data();
  if (id3v2tag) {
    set_has_id3v2tag();
    _impl_.data_.id3v2tag_ = id3v2tag;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Message.Response.id3v2Tag)
}
inline ::ID3v2::ID3v2Tag* Response::_internal_mutable_id3v2tag() {
  if (!_internal_has_id3v2tag()) {
    clear_data();
    set_has_id3v2tag();
    _impl_.data_.id3v2tag_ =
        CreateMaybeMessage<::ID3v2::ID3v2Tag>(GetArenaForAllocation());
  }
  return _impl_.data_.id3v2tag_;
}
inline ::ID3v2::ID3v2Tag* Response::mutable_id3v2tag() {
  ::ID3v2::ID3v2Tag* _msg = _internal_mutable_id3v2tag();
  // @@protoc_insertion_point(field_mutable:Message.Response.id3v2Tag)
  return _msg;
}

// .Message.Response.ResponseType response = 2;
inline bool Response::_internal_has_response() const {
  return data_case() == kResponse;
}
inline bool Response::has_response() const { return _internal_has_response(); }
inline void Response::set_has_response() { _impl_._oneof_case_[0] = kResponse; }
inline void Response::clear_response() {
  if (_internal_has_response()) {
    _impl_.data_.response_ = 0;
    clear_has_data();
  }
}
inline ::Message::Response_ResponseType Response::_internal_response() const {
  if (_internal_has_response()) {
    return static_cast<::Message::Response_ResponseType>(
        _impl_.data_.response_);
  }
  return static_cast<::Message::Response_ResponseType>(0);
}
inline ::Message::Response_ResponseType Response::response() const {
  // @@protoc_insertion_point(field_get:Message.Response.response)
  return _internal_response();
}
inline void Response::_internal_set_response(
    ::Message::Response_ResponseType value) {
  if (!_internal_has_response()) {
    clear_data();
    set_has_response();
  }
  _impl_.data_.response_ = value;
}
inline void Response::set_response(::Message::Response_ResponseType value) {
  _internal_set_response(value);
  // @@protoc_insertion_point(field_set:Message.Response.response)
}

inline bool Response::has_data() const { return data_case() != DATA_NOT_SET; }
inline void Response::clear_has_data() {
  _impl_._oneof_case_[0] = DATA_NOT_SET;
}
inline Response::DataCase Response::data_case() const {
  return Response::DataCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

PROTOBUF_NAMESPACE_OPEN

template <>
struct is_proto_enum<::Message::Request_RequestType> : ::std::true_type {};
template <>
inline const EnumDescriptor*
GetEnumDescriptor<::Message::Request_RequestType>() {
  return ::Message::Request_RequestType_descriptor();
}
template <>
struct is_proto_enum<::Message::Response_ResponseType> : ::std::true_type {};
template <>
inline const EnumDescriptor*
GetEnumDescriptor<::Message::Response_ResponseType>() {
  return ::Message::Response_ResponseType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Message_2eproto
